name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install system dependencies
        run: | 
         sudo apt-get update  -y 
         sudo apt-get install -y gcc-12 g++-12 libnuma-dev
         sudo update-alternatives \
           --install /usr/bin/gcc gcc /usr/bin/gcc-12 10 \
           --slave /usr/bin/g++ g++ /usr/bin/g++-12
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r setup_requirements.txt
      - name: Build and test with tox
        run: tox -e py
